# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20111115032209) do

  create_table "awps", :force => true do |t|
    t.string   "product_name"
    t.string   "ndc"
    t.string   "manufacturer_name"
    t.date     "effective_date"
    t.string   "manufacturer_cmsid"
    t.string   "package_cmsid"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "awps", ["ndc"], :name => "index_awps_on_ndc"

  create_table "card_locations", :force => true do |t|
    t.integer  "card_id"
    t.integer  "location_id"
    t.string   "location_type"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "cards", :force => true do |t|
    t.string   "card_number"
    t.date     "exp_date"
    t.string   "cvv"
    t.string   "issuer"
    t.integer  "lot_id"
    t.integer  "location_id"
    t.string   "location_type"
    t.integer  "product_id"
    t.date     "activated_date"
    t.integer  "issuer_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "lot_number"
  end

  create_table "companies", :force => true do |t|
    t.string   "company_name"
    t.binary   "company_logo"
    t.integer  "mfg_code"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "customers", :force => true do |t|
    t.string   "first_name"
    t.string   "middle_initial"
    t.string   "last_name"
    t.string   "address1"
    t.string   "address2"
    t.string   "city"
    t.string   "state"
    t.string   "zip"
    t.string   "phone"
    t.string   "gender"
    t.string   "email"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "deas", :force => true do |t|
    t.string   "dea_class_code"
    t.string   "dea_class_desc"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "deas", ["dea_class_code"], :name => "index_deas_on_dea_class_code"

  create_table "employees", :force => true do |t|
    t.string   "first"
    t.string   "middle_initial"
    t.string   "last"
    t.string   "position"
    t.string   "address1"
    t.string   "address2"
    t.string   "city"
    t.string   "state"
    t.string   "zip"
    t.string   "country"
    t.string   "phone"
    t.string   "territory"
    t.integer  "company_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "exdrugs", :force => true do |t|
    t.string   "exceptional_drug"
    t.string   "exceptional_drug_desc"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "exdrugs", ["exceptional_drug"], :name => "index_exdrugs_on_exceptional_drug"

  create_table "expgenrcs", :force => true do |t|
    t.integer  "gcr_code"
    t.string   "gcr_exp_name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "expgenrcs", ["gcr_code"], :name => "index_expgenrcs_on_gcr_code"

  create_table "expstrens", :force => true do |t|
    t.integer  "strength_code"
    t.string   "strength_exp_name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "expstrens", ["strength_code"], :name => "index_expstrens_on_strength_code"

  create_table "forms", :force => true do |t|
    t.string   "form_code"
    t.string   "master_form_code"
    t.string   "form_desc"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "forms", ["form_code"], :name => "index_forms_on_form_code"

  create_table "gcrs", :force => true do |t|
    t.integer  "gcr_code"
    t.string   "gcr_name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "gcrs", ["gcr_code"], :name => "index_gcrs_on_gcr_code"

  create_table "gfcs", :force => true do |t|
    t.integer  "gfc"
    t.integer  "gfc_master_code"
    t.integer  "gcr_code"
    t.string   "form_code"
    t.integer  "strength_code"
    t.string   "roa_code"
    t.string   "gfc_deact"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "gfcs", ["gcr_code"], :name => "index_gfcs_on_gcr_code"

  create_table "issuers", :force => true do |t|
    t.string   "name"
    t.text     "notes"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "jcodes", :force => true do |t|
    t.string   "j_code"
    t.string   "j_code_desc"
    t.string   "ndc"
    t.string   "product_name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "jcodes", ["ndc"], :name => "index_jcodes_on_ndc"

  create_table "lbly2ks", :force => true do |t|
    t.integer  "mfg_code"
    t.string   "labeler_code"
    t.integer  "rebate_status"
    t.date     "rebate_effective_date"
    t.date     "rebate_termination_date"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "lbly2ks", ["mfg_code"], :name => "index_lbly2ks_on_mfg_code"

  create_table "lots", :force => true do |t|
    t.integer  "location_id"
    t.string   "location_type"
    t.integer  "quantity"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "lot_number"
  end

  create_table "measures", :force => true do |t|
    t.string   "measure_code"
    t.string   "measure_desc"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "mforms", :force => true do |t|
    t.string   "master_form_code"
    t.string   "master_form_desc"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "mforms", ["master_form_code"], :name => "index_mforms_on_master_form_code"

  create_table "mfrs", :force => true do |t|
    t.string   "mfg_name_long"
    t.string   "mfg_name"
    t.integer  "mfg_code"
    t.string   "address1"
    t.string   "address2"
    t.string   "city"
    t.string   "state"
    t.string   "zip"
    t.integer  "phone_area_code"
    t.integer  "phone_number"
    t.integer  "fax_area_code"
    t.integer  "fax_number"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "mfrs", ["mfg_code"], :name => "index_mfrs_on_mfg_code"

  create_table "npis", :force => true do |t|
    t.integer  "npi"
    t.integer  "entity_type_code"
    t.integer  "replacement_npi"
    t.string   "employer_identification_number"
    t.string   "provider_organization_name"
    t.string   "provider_last_name"
    t.string   "provider_first_name"
    t.string   "provider_middle_name"
    t.string   "provider_name_prefix_text"
    t.string   "provider_name_suffix_text"
    t.string   "provider_credential_text"
    t.string   "provider_other_organization_name"
    t.string   "provider_other_organization_name_type_code"
    t.string   "provider_other_last_name"
    t.string   "provider_other_first_name"
    t.string   "provider_other_middle_name"
    t.string   "provider_other_name_prefix_text"
    t.string   "provider_other_name_suffix_text"
    t.string   "provider_other_credential_text"
    t.integer  "provider_other_last_name_type_code"
    t.string   "provider_first_line_business_mailing_address"
    t.string   "provider_second_line_business_mailing_address"
    t.string   "provider_business_mailing_address_city_name"
    t.string   "provider_business_mailing_address_state_name"
    t.string   "provider_business_mailing_address_postal_code"
    t.string   "provider_business_mailing_address_country_code"
    t.string   "provider_business_mailing_address_telephone_number"
    t.string   "provider_business_mailing_address_fax_number"
    t.string   "provider_first_line_business_practice_location_address"
    t.string   "provider_second_line_business_practice_location_address"
    t.string   "provider_business_practice_location_address_city_name"
    t.string   "provider_business_practice_location_address_state_name"
    t.string   "provider_business_practice_location_address_postal_code"
    t.string   "provider_business_practice_location_address_country_code"
    t.string   "provider_business_practice_location_address_telephone_number"
    t.string   "provider_business_practice_location_address_fax_number"
    t.date     "provider_enumeration_date"
    t.date     "last_update_date"
    t.string   "npi_deactivation_reason_code"
    t.date     "npi_deactivation_date"
    t.date     "npi_reactivation_date"
    t.string   "provider_gender_code"
    t.string   "authorized_official_last_name"
    t.string   "authorized_official_first_name"
    t.string   "authorized_official_middle_name"
    t.string   "authorized_official_title_or_position"
    t.string   "authorized_official_telephone_number"
    t.string   "healthcare_provider_taxonomy_code_1"
    t.string   "provider_license_number_1"
    t.string   "provider_license_number_state_code_1"
    t.string   "healthcare_provider_primary_taxonomy_switch_1"
    t.string   "healthcare_provider_taxonomy_code_2"
    t.string   "provider_license_number_2"
    t.string   "provider_license_number_state_code_2"
    t.string   "healthcare_provider_primary_taxonomy_switch_2"
    t.string   "healthcare_provider_taxonomy_code_3"
    t.string   "provider_license_number_3"
    t.string   "provider_license_number_state_code_3"
    t.string   "healthcare_provider_primary_taxonomy_switch_3"
    t.string   "healthcare_provider_taxonomy_code_4"
    t.string   "provider_license_number_4"
    t.string   "provider_license_number_state_code_4"
    t.string   "healthcare_provider_primary_taxonomy_switch_4"
    t.string   "healthcare_provider_taxonomy_code_5"
    t.string   "provider_license_number_5"
    t.string   "provider_license_number_state_code_5"
    t.string   "healthcare_provider_primary_taxonomy_switch_5"
    t.string   "healthcare_provider_taxonomy_code_6"
    t.string   "provider_license_number_6"
    t.string   "provider_license_number_state_code_6"
    t.string   "healthcare_provider_primary_taxonomy_switch_6"
    t.string   "healthcare_provider_taxonomy_code_7"
    t.string   "provider_license_number_7"
    t.string   "provider_license_number_state_code_7"
    t.string   "healthcare_provider_primary_taxonomy_switch_7"
    t.string   "healthcare_provider_taxonomy_code_8"
    t.string   "provider_license_number_8"
    t.string   "provider_license_number_state_code_8"
    t.string   "healthcare_provider_primary_taxonomy_switch_8"
    t.string   "healthcare_provider_taxonomy_code_9"
    t.string   "provider_license_number_9"
    t.string   "provider_license_number_state_code_9"
    t.string   "healthcare_provider_primary_taxonomy_switch_9"
    t.string   "healthcare_provider_taxonomy_code_10"
    t.string   "provider_license_number_10"
    t.string   "provider_license_number_state_code_10"
    t.string   "healthcare_provider_primary_taxonomy_switch_10"
    t.string   "healthcare_provider_taxonomy_code_11"
    t.string   "provider_license_number_11"
    t.string   "provider_license_number_state_code_11"
    t.string   "healthcare_provider_primary_taxonomy_switch_11"
    t.string   "healthcare_provider_taxonomy_code_12"
    t.string   "provider_license_number_12"
    t.string   "provider_license_number_state_code_12"
    t.string   "healthcare_provider_primary_taxonomy_switch_12"
    t.string   "healthcare_provider_taxonomy_code_13"
    t.string   "provider_license_number_13"
    t.string   "provider_license_number_state_code_13"
    t.string   "healthcare_provider_primary_taxonomy_switch_13"
    t.string   "healthcare_provider_taxonomy_code_14"
    t.string   "provider_license_number_14"
    t.string   "provider_license_number_state_code_14"
    t.string   "healthcare_provider_primary_taxonomy_switch_14"
    t.string   "healthcare_provider_taxonomy_code_15"
    t.string   "provider_license_number_15"
    t.string   "provider_license_number_state_code_15"
    t.string   "healthcare_provider_primary_taxonomy_switch_15"
    t.string   "other_provider_identifier_1"
    t.string   "other_provider_identifier_type_code_1"
    t.string   "other_provider_identifier_state_1"
    t.string   "other_provider_identifier_issuer_1"
    t.string   "other_provider_identifier_2"
    t.string   "other_provider_identifier_type_code_2"
    t.string   "other_provider_identifier_state_2"
    t.string   "other_provider_identifier_issuer_2"
    t.string   "other_provider_identifier_3"
    t.string   "other_provider_identifier_type_code_3"
    t.string   "other_provider_identifier_state_3"
    t.string   "other_provider_identifier_issuer_3"
    t.string   "other_provider_identifier_4"
    t.string   "other_provider_identifier_type_code_4"
    t.string   "other_provider_identifier_state_4"
    t.string   "other_provider_identifier_issuer_4"
    t.string   "other_provider_identifier_5"
    t.string   "other_provider_identifier_type_code_5"
    t.string   "other_provider_identifier_state_5"
    t.string   "other_provider_identifier_issuer_5"
    t.string   "other_provider_identifier_6"
    t.string   "other_provider_identifier_type_code_6"
    t.string   "other_provider_identifier_state_6"
    t.string   "other_provider_identifier_issuer_6"
    t.string   "other_provider_identifier_7"
    t.string   "other_provider_identifier_type_code_7"
    t.string   "other_provider_identifier_state_7"
    t.string   "other_provider_identifier_issuer_7"
    t.string   "other_provider_identifier_8"
    t.string   "other_provider_identifier_type_code_8"
    t.string   "other_provider_identifier_state_8"
    t.string   "other_provider_identifier_issuer_8"
    t.string   "other_provider_identifier_9"
    t.string   "other_provider_identifier_type_code_9"
    t.string   "other_provider_identifier_state_9"
    t.string   "other_provider_identifier_issuer_9"
    t.string   "other_provider_identifier_10"
    t.string   "other_provider_identifier_type_code_10"
    t.string   "other_provider_identifier_state_10"
    t.string   "other_provider_identifier_issuer_10"
    t.string   "other_provider_identifier_11"
    t.string   "other_provider_identifier_type_code_11"
    t.string   "other_provider_identifier_state_11"
    t.string   "other_provider_identifier_issuer_11"
    t.string   "other_provider_identifier_12"
    t.string   "other_provider_identifier_type_code_12"
    t.string   "other_provider_identifier_state_12"
    t.string   "other_provider_identifier_issuer_12"
    t.string   "other_provider_identifier_13"
    t.string   "other_provider_identifier_type_code_13"
    t.string   "other_provider_identifier_state_13"
    t.string   "other_provider_identifier_issuer_13"
    t.string   "other_provider_identifier_14"
    t.string   "other_provider_identifier_type_code_14"
    t.string   "other_provider_identifier_state_14"
    t.string   "other_provider_identifier_issuer_14"
    t.string   "other_provider_identifier_15"
    t.string   "other_provider_identifier_type_code_15"
    t.string   "other_provider_identifier_state_15"
    t.string   "other_provider_identifier_issuer_15"
    t.string   "other_provider_identifier_16"
    t.string   "other_provider_identifier_type_code_16"
    t.string   "other_provider_identifier_state_16"
    t.string   "other_provider_identifier_issuer_16"
    t.string   "other_provider_identifier_17"
    t.string   "other_provider_identifier_type_code_17"
    t.string   "other_provider_identifier_state_17"
    t.string   "other_provider_identifier_issuer_17"
    t.string   "other_provider_identifier_18"
    t.string   "other_provider_identifier_type_code_18"
    t.string   "other_provider_identifier_state_18"
    t.string   "other_provider_identifier_issuer_18"
    t.string   "other_provider_identifier_19"
    t.string   "other_provider_identifier_type_code_19"
    t.string   "other_provider_identifier_state_19"
    t.string   "other_provider_identifier_issuer_19"
    t.string   "other_provider_identifier_20"
    t.string   "other_provider_identifier_type_code_20"
    t.string   "other_provider_identifier_state_20"
    t.string   "other_provider_identifier_issuer_20"
    t.string   "other_provider_identifier_21"
    t.string   "other_provider_identifier_type_code_21"
    t.string   "other_provider_identifier_state_21"
    t.string   "other_provider_identifier_issuer_21"
    t.string   "other_provider_identifier_22"
    t.string   "other_provider_identifier_type_code_22"
    t.string   "other_provider_identifier_state_22"
    t.string   "other_provider_identifier_issuer_22"
    t.string   "other_provider_identifier_23"
    t.string   "other_provider_identifier_type_code_23"
    t.string   "other_provider_identifier_state_23"
    t.string   "other_provider_identifier_issuer_23"
    t.string   "other_provider_identifier_24"
    t.string   "other_provider_identifier_type_code_24"
    t.string   "other_provider_identifier_state_24"
    t.string   "other_provider_identifier_issuer_24"
    t.string   "other_provider_identifier_25"
    t.string   "other_provider_identifier_type_code_25"
    t.string   "other_provider_identifier_state_25"
    t.string   "other_provider_identifier_issuer_25"
    t.string   "other_provider_identifier_26"
    t.string   "other_provider_identifier_type_code_26"
    t.string   "other_provider_identifier_state_26"
    t.string   "other_provider_identifier_issuer_26"
    t.string   "other_provider_identifier_27"
    t.string   "other_provider_identifier_type_code_27"
    t.string   "other_provider_identifier_state_27"
    t.string   "other_provider_identifier_issuer_27"
    t.string   "other_provider_identifier_28"
    t.string   "other_provider_identifier_type_code_28"
    t.string   "other_provider_identifier_state_28"
    t.string   "other_provider_identifier_issuer_28"
    t.string   "other_provider_identifier_29"
    t.string   "other_provider_identifier_type_code_29"
    t.string   "other_provider_identifier_state_29"
    t.string   "other_provider_identifier_issuer_29"
    t.string   "other_provider_identifier_30"
    t.string   "other_provider_identifier_type_code_30"
    t.string   "other_provider_identifier_state_30"
    t.string   "other_provider_identifier_issuer_30"
    t.string   "other_provider_identifier_31"
    t.string   "other_provider_identifier_type_code_31"
    t.string   "other_provider_identifier_state_31"
    t.string   "other_provider_identifier_issuer_31"
    t.string   "other_provider_identifier_32"
    t.string   "other_provider_identifier_type_code_32"
    t.string   "other_provider_identifier_state_32"
    t.string   "other_provider_identifier_issuer_32"
    t.string   "other_provider_identifier_33"
    t.string   "other_provider_identifier_type_code_33"
    t.string   "other_provider_identifier_state_33"
    t.string   "other_provider_identifier_issuer_33"
    t.string   "other_provider_identifier_34"
    t.string   "other_provider_identifier_type_code_34"
    t.string   "other_provider_identifier_state_34"
    t.string   "other_provider_identifier_issuer_34"
    t.string   "other_provider_identifier_35"
    t.string   "other_provider_identifier_type_code_35"
    t.string   "other_provider_identifier_state_35"
    t.string   "other_provider_identifier_issuer_35"
    t.string   "other_provider_identifier_36"
    t.string   "other_provider_identifier_type_code_36"
    t.string   "other_provider_identifier_state_36"
    t.string   "other_provider_identifier_issuer_36"
    t.string   "other_provider_identifier_37"
    t.string   "other_provider_identifier_type_code_37"
    t.string   "other_provider_identifier_state_37"
    t.string   "other_provider_identifier_issuer_37"
    t.string   "other_provider_identifier_38"
    t.string   "other_provider_identifier_type_code_38"
    t.string   "other_provider_identifier_state_38"
    t.string   "other_provider_identifier_issuer_38"
    t.string   "other_provider_identifier_39"
    t.string   "other_provider_identifier_type_code_39"
    t.string   "other_provider_identifier_state_39"
    t.string   "other_provider_identifier_issuer_39"
    t.string   "other_provider_identifier_40"
    t.string   "other_provider_identifier_type_code_40"
    t.string   "other_provider_identifier_state_40"
    t.string   "other_provider_identifier_issuer_40"
    t.string   "other_provider_identifier_41"
    t.string   "other_provider_identifier_type_code_41"
    t.string   "other_provider_identifier_state_41"
    t.string   "other_provider_identifier_issuer_41"
    t.string   "other_provider_identifier_42"
    t.string   "other_provider_identifier_type_code_42"
    t.string   "other_provider_identifier_state_42"
    t.string   "other_provider_identifier_issuer_42"
    t.string   "other_provider_identifier_43"
    t.string   "other_provider_identifier_type_code_43"
    t.string   "other_provider_identifier_state_43"
    t.string   "other_provider_identifier_issuer_43"
    t.string   "other_provider_identifier_44"
    t.string   "other_provider_identifier_type_code_44"
    t.string   "other_provider_identifier_state_44"
    t.string   "other_provider_identifier_issuer_44"
    t.string   "other_provider_identifier_45"
    t.string   "other_provider_identifier_type_code_45"
    t.string   "other_provider_identifier_state_45"
    t.string   "other_provider_identifier_issuer_45"
    t.string   "other_provider_identifier_46"
    t.string   "other_provider_identifier_type_code_46"
    t.string   "other_provider_identifier_state_46"
    t.string   "other_provider_identifier_issuer_46"
    t.string   "other_provider_identifier_47"
    t.string   "other_provider_identifier_type_code_47"
    t.string   "other_provider_identifier_state_47"
    t.string   "other_provider_identifier_issuer_47"
    t.string   "other_provider_identifier_48"
    t.string   "other_provider_identifier_type_code_48"
    t.string   "other_provider_identifier_state_48"
    t.string   "other_provider_identifier_issuer_48"
    t.string   "other_provider_identifier_49"
    t.string   "other_provider_identifier_type_code_49"
    t.string   "other_provider_identifier_state_49"
    t.string   "other_provider_identifier_issuer_49"
    t.string   "other_provider_identifier_50"
    t.string   "other_provider_identifier_type_code_50"
    t.string   "other_provider_identifier_state_50"
    t.string   "other_provider_identifier_issuer_50"
    t.string   "is_sole_proprietor"
    t.string   "is_organization_subpart"
    t.string   "parent_organization_lbn"
    t.string   "parent_organization_tin"
    t.string   "authorized_official_name_prefix_text"
    t.string   "authorized_official_name_suffix_text"
    t.string   "authorized_official_credential_text"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "oranges", :force => true do |t|
    t.string   "orange_book_code"
    t.string   "orange_book_desc"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "oranges", ["orange_book_code"], :name => "index_oranges_on_orange_book_code"

  create_table "packstrens", :force => true do |t|
    t.integer  "package_ID"
    t.string   "ndc"
    t.integer  "strength_code"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "packstrens", ["ndc"], :name => "index_packstrens_on_ndc"

  create_table "prodcats", :force => true do |t|
    t.string   "product_category"
    t.string   "product_cat_desc"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "prodcats", ["product_category"], :name => "index_prodcats_on_product_category"

  create_table "promotions", :force => true do |t|
    t.string   "name"
    t.date     "start_date"
    t.date     "end_date"
    t.integer  "product_id"
    t.text     "description"
    t.decimal  "value"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "providers", :force => true do |t|
    t.integer  "npi"
    t.string   "business_name"
    t.string   "address1"
    t.string   "address2"
    t.string   "city"
    t.string   "state"
    t.string   "zip"
    t.string   "phone1"
    t.string   "fax"
    t.string   "contact"
    t.string   "first"
    t.string   "last"
    t.string   "title"
    t.string   "specialty"
    t.integer  "sales"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "license"
    t.string   "license_state"
  end

  create_table "roas", :force => true do |t|
    t.string   "roa_code"
    t.string   "roa_name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "roas", ["roa_code"], :name => "index_roas_on_roa_code"

  create_table "skus", :force => true do |t|
    t.string   "record_change"
    t.date     "record_change_date"
    t.date     "price_change_date"
    t.string   "add_flag"
    t.date     "add_date"
    t.string   "deactivate_flag"
    t.date     "deactivate_date"
    t.string   "reactivate_flag"
    t.date     "reactivate_date"
    t.string   "filler1"
    t.date     "prev_ndc_awp_eff_date"
    t.decimal  "prev_ndc_awp_pack_price"
    t.date     "prev_ndc_disc_date"
    t.string   "ndc"
    t.string   "filler2"
    t.string   "ndc_orig_config"
    t.string   "ndc10"
    t.string   "ndc_change_flag"
    t.string   "prev_ndc"
    t.string   "prev_ndc_config"
    t.string   "prev_ndc10"
    t.string   "roa_code"
    t.string   "roa_name"
    t.string   "master_form_code"
    t.string   "master_form_desc"
    t.string   "product_name"
    t.string   "additional_desc"
    t.string   "mfg_name_long"
    t.string   "product_category"
    t.string   "product_cat_desc"
    t.string   "solid_liquid"
    t.string   "form_code"
    t.string   "form_desc"
    t.string   "metric_size"
    t.string   "strength_name"
    t.string   "orange_book_code"
    t.string   "orange_book_desc"
    t.string   "filler3"
    t.string   "orange_book_std_flag"
    t.string   "unit_dose_flag"
    t.string   "dispensing_unit_flag"
    t.string   "package_size"
    t.string   "package_qty_code"
    t.string   "product_size"
    t.integer  "measure_code"
    t.string   "measure_desc"
    t.string   "filler4"
    t.string   "top_volume_rank"
    t.integer  "single_source_flag"
    t.string   "maintenance_drug_flag"
    t.string   "exceptional_drug"
    t.string   "exceptional_drug_desc"
    t.string   "dea_class_code"
    t.string   "dea_class_desc"
    t.string   "filler5"
    t.string   "filler6"
    t.string   "desi_drug_flag"
    t.date     "desi_effective_date"
    t.string   "thera_class_code"
    t.string   "thera_class_desc"
    t.integer  "generic_class_code"
    t.integer  "gcr_code"
    t.string   "gcr_name"
    t.string   "gcr_exp_name"
    t.integer  "gfc_code"
    t.integer  "stc_package_size"
    t.string   "unit_of_measure"
    t.integer  "mfg_code"
    t.string   "wac_start_flag"
    t.decimal  "wac_p_price"
    t.decimal  "wac_u_price"
    t.date     "wac_eff_date"
    t.decimal  "wac1pre_p_price"
    t.decimal  "wac1pre_u_price"
    t.date     "wac1pre_eff_date"
    t.decimal  "wac2pre_p_price"
    t.decimal  "wac2pre_u_price"
    t.date     "wac2pre_eff_date"
    t.string   "filler7"
    t.string   "filler8"
    t.string   "filler9"
    t.string   "awp_start_flag"
    t.decimal  "awp_p_price"
    t.decimal  "awp_u_price"
    t.date     "awp_eff_date"
    t.decimal  "awp1pre_p_price"
    t.decimal  "awp1pre_u_price"
    t.date     "awp1pre_eff_date"
    t.decimal  "awp2pre_p_price"
    t.decimal  "awp2pre_u_price"
    t.date     "awp2pre_eff_date"
    t.string   "dp_start_flag"
    t.decimal  "dp_p_price"
    t.decimal  "dp_u_price"
    t.date     "dp_eff_date"
    t.decimal  "dp1pre_p_price"
    t.decimal  "dp1pre_u_price"
    t.date     "dp1pre_eff_date"
    t.decimal  "dp2pre_p_price"
    t.decimal  "dp2pre_u_price"
    t.date     "dp2pre_eff_date"
    t.string   "ful_start_flag"
    t.decimal  "ful_p_price"
    t.decimal  "ful_u_price"
    t.date     "ful_eff_date"
    t.decimal  "ful_pre_p_price"
    t.decimal  "ful_pre_u_price"
    t.date     "ful_pre_eff_date"
    t.decimal  "ful2_pre_p_price"
    t.decimal  "ful2_pre_u_price"
    t.date     "ful2_pre_eff_date"
    t.string   "srp_start_flag"
    t.decimal  "srp_p_price"
    t.decimal  "srp_u_price"
    t.date     "srp_eff_date"
    t.decimal  "srp1pre_p_price"
    t.decimal  "srp1pre_u_price"
    t.date     "srp1pre_eff_date"
    t.decimal  "srp2pre_p_price"
    t.decimal  "srp2pre_u_price"
    t.date     "srp2pre_eff_date"
    t.string   "j_code"
    t.string   "j_code_desc"
    t.string   "labeler_code"
    t.integer  "rebate_status"
    t.date     "rebate_effective_date"
    t.date     "rebate_termination_date"
    t.integer  "package_ID"
    t.integer  "strength_code"
    t.string   "strength_exp_name"
    t.date     "effective_date"
    t.string   "manufacturer_name"
    t.string   "manufacturer_cmsid"
    t.string   "package_cmsid"
    t.integer  "gfc_master_code"
    t.string   "gfc_deact"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "strength_name_long"
  end

  add_index "skus", ["ndc"], :name => "index_skus_on_ndc"

  create_table "states", :force => true do |t|
    t.string   "name"
    t.string   "code"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "strengths", :force => true do |t|
    t.integer  "strength_code"
    t.string   "strength_name"
    t.string   "strength_name_long"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "strengths", ["strength_code"], :name => "index_strengths_on_strength_code"

  create_table "strens", :force => true do |t|
    t.integer  "strength_code"
    t.string   "strength_name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "strens", ["strength_code"], :name => "index_strens_on_strength_code"

  create_table "territories", :force => true do |t|
    t.string   "territory_name"
    t.string   "zipcode"
    t.string   "zip_label"
    t.integer  "district_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "thers", :force => true do |t|
    t.string   "thera_class_code"
    t.string   "thera_class_desc"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "thera_class_code_int"
  end

  add_index "thers", ["thera_class_code"], :name => "index_thers_on_thera_class_code"

  create_table "warehouses", :force => true do |t|
    t.string   "name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "zipcodes", :force => true do |t|
    t.string   "zipcode"
    t.string   "primary_record"
    t.integer  "population"
    t.integer  "households_per_zipcode"
    t.integer  "white_population"
    t.integer  "black_population"
    t.integer  "hispanic_population"
    t.integer  "asian_population"
    t.integer  "hawaiian_population"
    t.integer  "indian_population"
    t.integer  "other_population"
    t.integer  "male_population"
    t.integer  "female_population"
    t.decimal  "persons_per_household"
    t.integer  "average_house_value"
    t.integer  "income_per_household"
    t.decimal  "median_age"
    t.decimal  "median_age_male"
    t.decimal  "median_age_female"
    t.decimal  "latitude"
    t.decimal  "longitude"
    t.integer  "elevation"
    t.string   "state"
    t.string   "state_full_name"
    t.string   "city_type"
    t.string   "city_alias_abbreviation"
    t.string   "area_code"
    t.string   "city"
    t.string   "city_alias_name"
    t.string   "county"
    t.string   "county_fips"
    t.string   "state_fips"
    t.string   "time_zone"
    t.string   "daylight_saving"
    t.string   "msa"
    t.string   "pmsa"
    t.string   "csa"
    t.string   "cbsa"
    t.string   "cbsa_div"
    t.string   "cbsa_type"
    t.string   "cbs_aname"
    t.string   "msa_name"
    t.string   "pmsa_name"
    t.string   "region"
    t.string   "division"
    t.string   "mailing_name"
    t.integer  "number_of_businesses"
    t.integer  "number_of_employees"
    t.integer  "business_first_quarter_payroll"
    t.integer  "business_annual_payroll"
    t.string   "business_employment_flag"
    t.integer  "growth_rank"
    t.integer  "growth_housing_units_2003"
    t.integer  "growth_housing_units_2004"
    t.integer  "growth_increase_number"
    t.decimal  "growth_increase_percentage"
    t.integer  "cbsa_pop_2003"
    t.integer  "cbsa_div_pop_2003"
    t.string   "congressional_district"
    t.string   "congressional_land_area"
    t.integer  "delivery_residential"
    t.integer  "delivery_business"
    t.integer  "delivery_total"
    t.string   "preferred_last_line_key"
    t.string   "classification_code"
    t.string   "multi_county"
    t.string   "csa_name"
    t.string   "cbsa_div_name"
    t.string   "city_state_key"
    t.integer  "population_estimate"
    t.decimal  "land_area"
    t.decimal  "water_area"
    t.string   "city_alias_code"
    t.string   "city_mixed_case"
    t.string   "city_alias_mixed_case"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
