class CreateSkus < ActiveRecord::Migration
  def change
    create_table :skus do |t|
      t.string :record_change
      t.date :record_change_date
      t.date :price_change_date
      t.string :add_flag
      t.date :add_date
      t.string :deactivate_flag
      t.date :deactivate_date
      t.string :reactivate_flag
      t.date :reactivate_date
      t.string :filler1
      t.date :prev_ndc_awp_eff_date
      t.decimal :prev_ndc_awp_pack_price
      t.date :prev_ndc_disc_date
      t.string :ndc
      t.string :filler2
      t.string :ndc_orig_config
      t.string :ndc10
      t.string :ndc_change_flag
      t.string :prev_ndc
      t.string :prev_ndc_config
      t.string :prev_ndc10
      t.string :roa_code
      t.string :roa_name
      t.string :master_form_code
      t.string :master_form_desc
      t.string :product_name
      t.string :additional_desc
      t.string :mfg_name_long
      t.string :product_category
      t.string :product_cat_desc
      t.string :solid_liquid
      t.string :form_code
      t.string :form_desc
      t.string :metric_size
      t.string :strength_name
      t.string :StrengthNameLong
      t.string :orange_book_code
      t.string :orange_book_desc
      t.string :filler3
      t.string :orange_book_std_flag
      t.string :unit_dose_flag
      t.string :dispensing_unit_flag
      t.string :package_size
      t.string :package_qty_code
      t.string :product_size
      t.integer :measure_code
      t.string :measure_desc
      t.string :filler4
      t.string :top_volume_rank
      t.integer :single_source_flag
      t.string :maintenance_drug_flag
      t.string :exceptional_drug
      t.string :exceptional_drug_desc
      t.string :dea_class_code
      t.string :dea_class_desc
      t.string :filler5
      t.string :filler6
      t.string :desi_drug_flag
      t.date :desi_effective_date
      t.string :thera_class_code
      t.string :thera_class_desc
      t.integer :generic_class_code
      t.integer :gcr_code
      t.string :gcr_name
      t.string :gcr_exp_name
      t.integer :gfc_code
      t.integer :stc_package_size
      t.string :unit_of_measure
      t.integer :mfg_code
      t.string :wac_start_flag
      t.decimal :wac_p_price
      t.decimal :wac_u_price
      t.date :wac_eff_date
      t.decimal :wac1pre_p_price
      t.decimal :wac1pre_u_price
      t.date :wac1pre_eff_date
      t.decimal :wac2pre_p_price
      t.decimal :wac2pre_u_price
      t.date :wac2pre_eff_date
      t.string :filler7
      t.string :filler8
      t.string :filler9
      t.string :awp_start_flag
      t.decimal :awp_p_price
      t.decimal :awp_u_price
      t.date :awp_eff_date
      t.decimal :awp1pre_p_price
      t.decimal :awp1pre_u_price
      t.date :awp1pre_eff_date
      t.decimal :awp2pre_p_price
      t.decimal :awp2pre_u_price
      t.date :awp2pre_eff_date
      t.string :dp_start_flag
      t.decimal :dp_p_price
      t.decimal :dp_u_price
      t.date :dp_eff_date
      t.decimal :dp1pre_p_price
      t.decimal :dp1pre_u_price
      t.date :dp1pre_eff_date
      t.decimal :dp2pre_p_price
      t.decimal :dp2pre_u_price
      t.date :dp2pre_eff_date
      t.string :ful_start_flag
      t.decimal :ful_p_price
      t.decimal :ful_u_price
      t.date :ful_eff_date
      t.decimal :ful_pre_p_price
      t.decimal :ful_pre_u_price
      t.date :ful_pre_eff_date
      t.decimal :ful2_pre_p_price
      t.decimal :ful2_pre_u_price
      t.date :ful2_pre_eff_date
      t.string :srp_start_flag
      t.decimal :srp_p_price
      t.decimal :srp_u_price
      t.date :srp_eff_date
      t.decimal :srp1pre_p_price
      t.decimal :srp1pre_u_price
      t.date :srp1pre_eff_date
      t.decimal :srp2pre_p_price
      t.decimal :srp2pre_u_price
      t.date :srp2pre_eff_date
      t.string :j_code
      t.string :j_code_desc
      t.string :labeler_code
      t.integer :rebate_status
      t.date :rebate_effective_date
      t.date :rebate_termination_date
      t.integer :package_ID
      t.integer :strength_code
      t.string :strength_exp_name
      t.date :effective_date
      t.string :manufacturer_name
      t.string :manufacturer_cmsid
      t.string :package_cmsid
      t.integer :gfc_master_code
      t.string :gfc_deact

      t.timestamps
    end
  end
end
