class CreateNpis < ActiveRecord::Migration
  def change
    create_table :npis do |t|
      t.integer :npi
      t.integer :entity_type_code
      t.integer :replacement_npi
      t.string :employer_identification_number
      t.string :provider_organization_name
      t.string :provider_last_name
      t.string :provider_first_name
      t.string :provider_middle_name
      t.string :provider_name_prefix_text
      t.string :provider_name_suffix_text
      t.string :provider_credential_text
      t.string :provider_other_organization_name
      t.string :provider_other_organization_name_type_code
      t.string :provider_other_last_name
      t.string :provider_other_first_name
      t.string :provider_other_middle_name
      t.string :provider_other_name_prefix_text
      t.string :provider_other_name_suffix_text
      t.string :provider_other_credential_text
      t.integer :provider_other_last_name_type_code
      t.string :provider_first_line_business_mailing_address
      t.string :provider_second_line_business_mailing_address
      t.string :provider_business_mailing_address_city_name
      t.string :provider_business_mailing_address_state_name
      t.string :provider_business_mailing_address_postal_code
      t.string :provider_business_mailing_address_country_code
      t.string :provider_business_mailing_address_telephone_number
      t.string :provider_business_mailing_address_fax_number
      t.string :provider_first_line_business_practice_location_address
      t.string :provider_second_line_business_practice_location_address
      t.string :provider_business_practice_location_address_city_name
      t.string :provider_business_practice_location_address_state_name
      t.string :provider_business_practice_location_address_postal_code
      t.string :provider_business_practice_location_address_country_code
      t.string :provider_business_practice_location_address_telephone_number
      t.string :provider_business_practice_location_address_fax_number
      t.date :provider_enumeration_date
      t.date :last_update_date
      t.string :npi_deactivation_reason_code
      t.date :npi_deactivation_date
      t.date :npi_reactivation_date
      t.string :provider_gender_code
      t.string :authorized_official_last_name
      t.string :authorized_official_first_name
      t.string :authorized_official_middle_name
      t.string :authorized_official_title_or_position
      t.string :authorized_official_telephone_number
      t.string :healthcare_provider_taxonomy_code_1
      t.string :provider_license_number_1
      t.string :provider_license_number_state_code_1
      t.string :healthcare_provider_primary_taxonomy_switch_1
      t.string :healthcare_provider_taxonomy_code_2
      t.string :provider_license_number_2
      t.string :provider_license_number_state_code_2
      t.string :healthcare_provider_primary_taxonomy_switch_2
      t.string :healthcare_provider_taxonomy_code_3
      t.string :provider_license_number_3
      t.string :provider_license_number_state_code_3
      t.string :healthcare_provider_primary_taxonomy_switch_3
      t.string :healthcare_provider_taxonomy_code_4
      t.string :provider_license_number_4
      t.string :provider_license_number_state_code_4
      t.string :healthcare_provider_primary_taxonomy_switch_4
      t.string :healthcare_provider_taxonomy_code_5
      t.string :provider_license_number_5
      t.string :provider_license_number_state_code_5
      t.string :healthcare_provider_primary_taxonomy_switch_5
      t.string :healthcare_provider_taxonomy_code_6
      t.string :provider_license_number_6
      t.string :provider_license_number_state_code_6
      t.string :healthcare_provider_primary_taxonomy_switch_6
      t.string :healthcare_provider_taxonomy_code_7
      t.string :provider_license_number_7
      t.string :provider_license_number_state_code_7
      t.string :healthcare_provider_primary_taxonomy_switch_7
      t.string :healthcare_provider_taxonomy_code_8
      t.string :provider_license_number_8
      t.string :provider_license_number_state_code_8
      t.string :healthcare_provider_primary_taxonomy_switch_8
      t.string :healthcare_provider_taxonomy_code_9
      t.string :provider_license_number_9
      t.string :provider_license_number_state_code_9
      t.string :healthcare_provider_primary_taxonomy_switch_9
      t.string :healthcare_provider_taxonomy_code_10
      t.string :provider_license_number_10
      t.string :provider_license_number_state_code_10
      t.string :healthcare_provider_primary_taxonomy_switch_10
      t.string :healthcare_provider_taxonomy_code_11
      t.string :provider_license_number_11
      t.string :provider_license_number_state_code_11
      t.string :healthcare_provider_primary_taxonomy_switch_11
      t.string :healthcare_provider_taxonomy_code_12
      t.string :provider_license_number_12
      t.string :provider_license_number_state_code_12
      t.string :healthcare_provider_primary_taxonomy_switch_12
      t.string :healthcare_provider_taxonomy_code_13
      t.string :provider_license_number_13
      t.string :provider_license_number_state_code_13
      t.string :healthcare_provider_primary_taxonomy_switch_13
      t.string :healthcare_provider_taxonomy_code_14
      t.string :provider_license_number_14
      t.string :provider_license_number_state_code_14
      t.string :healthcare_provider_primary_taxonomy_switch_14
      t.string :healthcare_provider_taxonomy_code_15
      t.string :provider_license_number_15
      t.string :provider_license_number_state_code_15
      t.string :healthcare_provider_primary_taxonomy_switch_15
      t.string :other_provider_identifier_1
      t.string :other_provider_identifier_type_code_1
      t.string :other_provider_identifier_state_1
      t.string :other_provider_identifier_issuer_1
      t.string :other_provider_identifier_2
      t.string :other_provider_identifier_type_code_2
      t.string :other_provider_identifier_state_2
      t.string :other_provider_identifier_issuer_2
      t.string :other_provider_identifier_3
      t.string :other_provider_identifier_type_code_3
      t.string :other_provider_identifier_state_3
      t.string :other_provider_identifier_issuer_3
      t.string :other_provider_identifier_4
      t.string :other_provider_identifier_type_code_4
      t.string :other_provider_identifier_state_4
      t.string :other_provider_identifier_issuer_4
      t.string :other_provider_identifier_5
      t.string :other_provider_identifier_type_code_5
      t.string :other_provider_identifier_state_5
      t.string :other_provider_identifier_issuer_5
      t.string :other_provider_identifier_6
      t.string :other_provider_identifier_type_code_6
      t.string :other_provider_identifier_state_6
      t.string :other_provider_identifier_issuer_6
      t.string :other_provider_identifier_7
      t.string :other_provider_identifier_type_code_7
      t.string :other_provider_identifier_state_7
      t.string :other_provider_identifier_issuer_7
      t.string :other_provider_identifier_8
      t.string :other_provider_identifier_type_code_8
      t.string :other_provider_identifier_state_8
      t.string :other_provider_identifier_issuer_8
      t.string :other_provider_identifier_9
      t.string :other_provider_identifier_type_code_9
      t.string :other_provider_identifier_state_9
      t.string :other_provider_identifier_issuer_9
      t.string :other_provider_identifier_10
      t.string :other_provider_identifier_type_code_10
      t.string :other_provider_identifier_state_10
      t.string :other_provider_identifier_issuer_10
      t.string :other_provider_identifier_11
      t.string :other_provider_identifier_type_code_11
      t.string :other_provider_identifier_state_11
      t.string :other_provider_identifier_issuer_11
      t.string :other_provider_identifier_12
      t.string :other_provider_identifier_type_code_12
      t.string :other_provider_identifier_state_12
      t.string :other_provider_identifier_issuer_12
      t.string :other_provider_identifier_13
      t.string :other_provider_identifier_type_code_13
      t.string :other_provider_identifier_state_13
      t.string :other_provider_identifier_issuer_13
      t.string :other_provider_identifier_14
      t.string :other_provider_identifier_type_code_14
      t.string :other_provider_identifier_state_14
      t.string :other_provider_identifier_issuer_14
      t.string :other_provider_identifier_15
      t.string :other_provider_identifier_type_code_15
      t.string :other_provider_identifier_state_15
      t.string :other_provider_identifier_issuer_15
      t.string :other_provider_identifier_16
      t.string :other_provider_identifier_type_code_16
      t.string :other_provider_identifier_state_16
      t.string :other_provider_identifier_issuer_16
      t.string :other_provider_identifier_17
      t.string :other_provider_identifier_type_code_17
      t.string :other_provider_identifier_state_17
      t.string :other_provider_identifier_issuer_17
      t.string :other_provider_identifier_18
      t.string :other_provider_identifier_type_code_18
      t.string :other_provider_identifier_state_18
      t.string :other_provider_identifier_issuer_18
      t.string :other_provider_identifier_19
      t.string :other_provider_identifier_type_code_19
      t.string :other_provider_identifier_state_19
      t.string :other_provider_identifier_issuer_19
      t.string :other_provider_identifier_20
      t.string :other_provider_identifier_type_code_20
      t.string :other_provider_identifier_state_20
      t.string :other_provider_identifier_issuer_20
      t.string :other_provider_identifier_21
      t.string :other_provider_identifier_type_code_21
      t.string :other_provider_identifier_state_21
      t.string :other_provider_identifier_issuer_21
      t.string :other_provider_identifier_22
      t.string :other_provider_identifier_type_code_22
      t.string :other_provider_identifier_state_22
      t.string :other_provider_identifier_issuer_22
      t.string :other_provider_identifier_23
      t.string :other_provider_identifier_type_code_23
      t.string :other_provider_identifier_state_23
      t.string :other_provider_identifier_issuer_23
      t.string :other_provider_identifier_24
      t.string :other_provider_identifier_type_code_24
      t.string :other_provider_identifier_state_24
      t.string :other_provider_identifier_issuer_24
      t.string :other_provider_identifier_25
      t.string :other_provider_identifier_type_code_25
      t.string :other_provider_identifier_state_25
      t.string :other_provider_identifier_issuer_25
      t.string :other_provider_identifier_26
      t.string :other_provider_identifier_type_code_26
      t.string :other_provider_identifier_state_26
      t.string :other_provider_identifier_issuer_26
      t.string :other_provider_identifier_27
      t.string :other_provider_identifier_type_code_27
      t.string :other_provider_identifier_state_27
      t.string :other_provider_identifier_issuer_27
      t.string :other_provider_identifier_28
      t.string :other_provider_identifier_type_code_28
      t.string :other_provider_identifier_state_28
      t.string :other_provider_identifier_issuer_28
      t.string :other_provider_identifier_29
      t.string :other_provider_identifier_type_code_29
      t.string :other_provider_identifier_state_29
      t.string :other_provider_identifier_issuer_29
      t.string :other_provider_identifier_30
      t.string :other_provider_identifier_type_code_30
      t.string :other_provider_identifier_state_30
      t.string :other_provider_identifier_issuer_30
      t.string :other_provider_identifier_31
      t.string :other_provider_identifier_type_code_31
      t.string :other_provider_identifier_state_31
      t.string :other_provider_identifier_issuer_31
      t.string :other_provider_identifier_32
      t.string :other_provider_identifier_type_code_32
      t.string :other_provider_identifier_state_32
      t.string :other_provider_identifier_issuer_32
      t.string :other_provider_identifier_33
      t.string :other_provider_identifier_type_code_33
      t.string :other_provider_identifier_state_33
      t.string :other_provider_identifier_issuer_33
      t.string :other_provider_identifier_34
      t.string :other_provider_identifier_type_code_34
      t.string :other_provider_identifier_state_34
      t.string :other_provider_identifier_issuer_34
      t.string :other_provider_identifier_35
      t.string :other_provider_identifier_type_code_35
      t.string :other_provider_identifier_state_35
      t.string :other_provider_identifier_issuer_35
      t.string :other_provider_identifier_36
      t.string :other_provider_identifier_type_code_36
      t.string :other_provider_identifier_state_36
      t.string :other_provider_identifier_issuer_36
      t.string :other_provider_identifier_37
      t.string :other_provider_identifier_type_code_37
      t.string :other_provider_identifier_state_37
      t.string :other_provider_identifier_issuer_37
      t.string :other_provider_identifier_38
      t.string :other_provider_identifier_type_code_38
      t.string :other_provider_identifier_state_38
      t.string :other_provider_identifier_issuer_38
      t.string :other_provider_identifier_39
      t.string :other_provider_identifier_type_code_39
      t.string :other_provider_identifier_state_39
      t.string :other_provider_identifier_issuer_39
      t.string :other_provider_identifier_40
      t.string :other_provider_identifier_type_code_40
      t.string :other_provider_identifier_state_40
      t.string :other_provider_identifier_issuer_40
      t.string :other_provider_identifier_41
      t.string :other_provider_identifier_type_code_41
      t.string :other_provider_identifier_state_41
      t.string :other_provider_identifier_issuer_41
      t.string :other_provider_identifier_42
      t.string :other_provider_identifier_type_code_42
      t.string :other_provider_identifier_state_42
      t.string :other_provider_identifier_issuer_42
      t.string :other_provider_identifier_43
      t.string :other_provider_identifier_type_code_43
      t.string :other_provider_identifier_state_43
      t.string :other_provider_identifier_issuer_43
      t.string :other_provider_identifier_44
      t.string :other_provider_identifier_type_code_44
      t.string :other_provider_identifier_state_44
      t.string :other_provider_identifier_issuer_44
      t.string :other_provider_identifier_45
      t.string :other_provider_identifier_type_code_45
      t.string :other_provider_identifier_state_45
      t.string :other_provider_identifier_issuer_45
      t.string :other_provider_identifier_46
      t.string :other_provider_identifier_type_code_46
      t.string :other_provider_identifier_state_46
      t.string :other_provider_identifier_issuer_46
      t.string :other_provider_identifier_47
      t.string :other_provider_identifier_type_code_47
      t.string :other_provider_identifier_state_47
      t.string :other_provider_identifier_issuer_47
      t.string :other_provider_identifier_48
      t.string :other_provider_identifier_type_code_48
      t.string :other_provider_identifier_state_48
      t.string :other_provider_identifier_issuer_48
      t.string :other_provider_identifier_49
      t.string :other_provider_identifier_type_code_49
      t.string :other_provider_identifier_state_49
      t.string :other_provider_identifier_issuer_49
      t.string :other_provider_identifier_50
      t.string :other_provider_identifier_type_code_50
      t.string :other_provider_identifier_state_50
      t.string :other_provider_identifier_issuer_50
      t.string :is_sole_proprietor
      t.string :is_organization_subpart
      t.string :parent_organization_lbn
      t.string :parent_organization_tin
      t.string :authorized_official_name_prefix_text
      t.string :authorized_official_name_suffix_text
      t.string :authorized_official_credential_text

      t.timestamps
    end
  end
end
